const mockTransactions = [
  {
    id: "tx_123456",
    amount: 1250.5,
    currency: "USD",
    status: "completed",
    date: "2024-01-15T10:30:00Z",
    description: "Online purchase",
    merchant: "Tech Store Inc",
    customer: {
      name: "John Doe",
      email: "john@example.com",
    },
    paymentMethod: "credit_card",
    cardLast4: "1234",
    fees: 25.1,
  },
  {
    id: "tx_789012",
    amount: 799.99,
    currency: "USD",
    status: "pending",
    date: "2024-01-16T15:45:00Z",
    description: "Electronics purchase",
    merchant: "Gadget World",
    customer: {
      name: "Jane Smith",
      email: "jane@example.com",
    },
    paymentMethod: "debit_card",
    cardLast4: "5678",
    fees: 15.99,
  },
  {
    id: "tx_345678",
    amount: 50.0,
    currency: "USD",
    status: "failed",
    date: "2024-01-14T09:15:00Z",
    description: "Subscription renewal",
    merchant: "StreamFlix",
    customer: {
      name: "Bob Wilson",
      email: "bob@example.com",
    },
    paymentMethod: "credit_card",
    cardLast4: "9012",
    fees: 1.5,
  },
  {
    id: "tx_457891",
    amount: 120.99,
    currency: "USD",
    status: "completed",
    date: "2024-02-01T13:45:00Z",
    description: "Online course payment",
    merchant: "EduZone",
    customer: {
      name: "Alice Brown",
      email: "alice.b@example.com",
    },
    paymentMethod: "paypal",
    cardLast4: "6234",
    fees: 3.2,
  },
  {
    id: "tx_982341",
    amount: 89.5,
    currency: "USD",
    status: "pending",
    date: "2024-03-22T16:30:00Z",
    description: "Electronics purchase",
    merchant: "TechMart",
    customer: {
      name: "Carlos Reyes",
      email: "carlosr@example.com",
    },
    paymentMethod: "credit_card",
    cardLast4: "4567",
    fees: 2.1,
  },
  {
    id: "tx_876543",
    amount: 15.0,
    currency: "EUR",
    status: "completed",
    date: "2024-01-25T11:00:00Z",
    description: "Music download",
    merchant: "Soundify",
    customer: {
      name: "Dana Lee",
      email: "dlee@example.com",
    },
    paymentMethod: "credit_card",
    cardLast4: "1122",
    fees: 0.5,
  },
  {
    id: "tx_123987",
    amount: 249.99,
    currency: "USD",
    status: "failed",
    date: "2024-05-03T19:20:00Z",
    description: "Furniture order",
    merchant: "HomeStyle",
    customer: {
      name: "Evan Thomas",
      email: "evant@example.com",
    },
    paymentMethod: "paypal",
    cardLast4: "7788",
    fees: 4.5,
  },
  {
    id: "tx_564738",
    amount: 7.25,
    currency: "EUR",
    status: "pending",
    date: "2024-04-10T08:00:00Z",
    description: "E-book purchase",
    merchant: "ReadMore",
    customer: {
      name: "Fiona Green",
      email: "fiona.g@example.com",
    },
    paymentMethod: "credit_card",
    cardLast4: "3344",
    fees: 0.3,
  },
  {
    id: "tx_111999",
    amount: 320.0,
    currency: "USD",
    status: "completed",
    date: "2024-02-15T17:45:00Z",
    description: "Gym membership annual",
    merchant: "FitLife",
    customer: {
      name: "George Hall",
      email: "george.h@example.com",
    },
    paymentMethod: "debit_card",
    cardLast4: "9988",
    fees: 6.0,
  },
  {
    id: "tx_777555",
    amount: 39.99,
    currency: "USD",
    status: "failed",
    date: "2024-03-30T10:10:00Z",
    description: "Game purchase",
    merchant: "PlayZone",
    customer: {
      name: "Hannah Kim",
      email: "hannah.k@example.com",
    },
    paymentMethod: "credit_card",
    cardLast4: "5566",
    fees: 1.2,
  },
  {
    id: "tx_444222",
    amount: 99.0,
    currency: "USD",
    status: "completed",
    date: "2024-01-05T15:00:00Z",
    description: "Monthly groceries",
    merchant: "FreshMart",
    customer: {
      name: "Ian Wright",
      email: "ianw@example.com",
    },
    paymentMethod: "debit_card",
    cardLast4: "4455",
    fees: 2.0,
  },
  {
    id: "tx_666888",
    amount: 11.49,
    currency: "EUR",
    status: "pending",
    date: "2024-06-01T12:30:00Z",
    description: "App subscription",
    merchant: "NotePro",
    customer: {
      name: "Julia Chen",
      email: "jchen@example.com",
    },
    paymentMethod: "credit_card",
    cardLast4: "6677",
    fees: 0.4,
  },
  {
    id: "tx_222444",
    amount: 59.99,
    currency: "USD",
    status: "completed",
    date: "2024-04-18T14:55:00Z",
    description: "Running shoes",
    merchant: "SportX",
    customer: {
      name: "Kyle Johnson",
      email: "kylej@example.com",
    },
    paymentMethod: "paypal",
    cardLast4: "2211",
    fees: 2.7,
  },
  {
    id: "tx_888111",
    amount: 25.0,
    currency: "USD",
    status: "failed",
    date: "2024-05-28T09:40:00Z",
    description: "Meal delivery",
    merchant: "QuickEats",
    customer: {
      name: "Laura Davis",
      email: "laura.d@example.com",
    },
    paymentMethod: "debit_card",
    cardLast4: "8899",
    fees: 1.0,
  },
  {
    id: "tx_333666",
    amount: 5.99,
    currency: "USD",
    status: "completed",
    date: "2024-02-08T07:25:00Z",
    description: "Mobile app purchase",
    merchant: "AppStore",
    customer: {
      name: "Mark Allen",
      email: "marka@example.com",
    },
    paymentMethod: "credit_card",
    cardLast4: "3322",
    fees: 0.2,
  },
];

module.exports = { mockTransactions };
